/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hymerfania.countdown_mockups;

/**
 *
 * @author chymes
 */
public class Checklist_form extends javax.swing.JPanel {

    /**
     * Creates new form Checklist_form
     */
    public Checklist_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        timePanel = new javax.swing.JPanel();
        plusminus = new javax.swing.JLabel();
        seclab = new javax.swing.JLabel();
        warninglab = new javax.swing.JLabel();
        hrslab = new javax.swing.JLabel();
        dayslab = new javax.swing.JLabel();
        minlab = new javax.swing.JLabel();
        daysval = new javax.swing.JLabel();
        hrsval = new javax.swing.JLabel();
        minval = new javax.swing.JLabel();
        secval = new javax.swing.JLabel();
        colon1 = new javax.swing.JLabel();
        colon2 = new javax.swing.JLabel();
        colon3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        finishedTaskPanel = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jCheckBox9 = new javax.swing.JCheckBox();
        subtasksPanel0 = new javax.swing.JPanel();
        greenSpherejLabel0 = new javax.swing.JLabel();
        greenSpherejLabel1 = new javax.swing.JLabel();
        greenSpherejLabel2 = new javax.swing.JLabel();
        greenSpherejLabel3 = new javax.swing.JLabel();
        greenSpherejLabel4 = new javax.swing.JLabel();
        greenSpherejLabel5 = new javax.swing.JLabel();
        greenSpherejLabel6 = new javax.swing.JLabel();
        currentTaskPanel = new javax.swing.JPanel();
        subtasksPanel1 = new javax.swing.JPanel();
        greenSpherejLabel7 = new javax.swing.JLabel();
        greenSpherejLabel8 = new javax.swing.JLabel();
        greySpherejLabel0 = new javax.swing.JLabel();
        greySpherejLabel1 = new javax.swing.JLabel();
        greySpherejLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        taskPendingPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        subtasksPanel2 = new javax.swing.JPanel();
        greenSpherejLabel9 = new javax.swing.JLabel();
        greenSpherejLabel10 = new javax.swing.JLabel();
        greenSpherejLabel11 = new javax.swing.JLabel();
        greenSpherejLabel12 = new javax.swing.JLabel();
        greenSpherejLabel13 = new javax.swing.JLabel();
        greenSpherejLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jCheckBox7 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox5 = new javax.swing.JCheckBox();
        abandonedTaskPanel = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jCheckBox8 = new javax.swing.JCheckBox();
        failedTaskPanel = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox6 = new javax.swing.JCheckBox();
        subtasksPanel3 = new javax.swing.JPanel();
        greenSpherejLabel15 = new javax.swing.JLabel();
        greenSpherejLabel16 = new javax.swing.JLabel();
        greySpherejLabel4 = new javax.swing.JLabel();
        greySpherejLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        subtasksPanel4 = new javax.swing.JPanel();
        greenSpherejLabel17 = new javax.swing.JLabel();
        greenSpherejLabel18 = new javax.swing.JLabel();
        greenSpherejLabel20 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jCheckBox12 = new javax.swing.JCheckBox();
        subtasksPanel5 = new javax.swing.JPanel();
        greySpherejLabel02 = new javax.swing.JLabel();
        greySpherejLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        subtasksPanel6 = new javax.swing.JPanel();
        greySpherejLabel6 = new javax.swing.JLabel();
        greySpherejLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 1136));
        setMinimumSize(new java.awt.Dimension(640, 1136));
        setPreferredSize(new java.awt.Dimension(640, 1136));

        timePanel.setBackground(new java.awt.Color(255, 255, 255));
        timePanel.setAlignmentX(0.0F);
        timePanel.setAlignmentY(0.0F);
        timePanel.setMaximumSize(new java.awt.Dimension(640, 200));
        timePanel.setMinimumSize(new java.awt.Dimension(640, 100));
        timePanel.setPreferredSize(new java.awt.Dimension(640, 140));
        timePanel.setLayout(new java.awt.GridBagLayout());

        plusminus.setFont(new java.awt.Font("Lucida Grande", 1, 52)); // NOI18N
        plusminus.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        timePanel.add(plusminus, gridBagConstraints);

        seclab.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        seclab.setText("sec.");
        seclab.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        timePanel.add(seclab, gridBagConstraints);

        warninglab.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        warninglab.setForeground(new java.awt.Color(255, 0, 0));
        warninglab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/warning_16.png"))); // NOI18N
        warninglab.setText("Failure Warning!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.weightx = 2.0;
        timePanel.add(warninglab, gridBagConstraints);

        hrslab.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        hrslab.setText("hrs.");
        hrslab.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hrslab.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        timePanel.add(hrslab, gridBagConstraints);

        dayslab.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        dayslab.setText("days");
        dayslab.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.weightx = 0.5;
        timePanel.add(dayslab, gridBagConstraints);

        minlab.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        minlab.setText("min.");
        minlab.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        timePanel.add(minlab, gridBagConstraints);

        daysval.setFont(new java.awt.Font("Lucida Grande", 0, 82)); // NOI18N
        daysval.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        daysval.setText("00");
        daysval.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        daysval.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        timePanel.add(daysval, gridBagConstraints);

        hrsval.setFont(new java.awt.Font("Lucida Grande", 0, 82)); // NOI18N
        hrsval.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hrsval.setText("03");
        hrsval.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        hrsval.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        timePanel.add(hrsval, gridBagConstraints);

        minval.setFont(new java.awt.Font("Lucida Grande", 0, 82)); // NOI18N
        minval.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        minval.setText("12");
        minval.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        minval.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        timePanel.add(minval, gridBagConstraints);

        secval.setFont(new java.awt.Font("Lucida Grande", 0, 82)); // NOI18N
        secval.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        secval.setText("17");
        secval.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        secval.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 1;
        timePanel.add(secval, gridBagConstraints);

        colon1.setFont(new java.awt.Font("Lucida Grande", 0, 82)); // NOI18N
        colon1.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        timePanel.add(colon1, gridBagConstraints);

        colon2.setFont(new java.awt.Font("Lucida Grande", 0, 82)); // NOI18N
        colon2.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        timePanel.add(colon2, gridBagConstraints);

        colon3.setFont(new java.awt.Font("Lucida Grande", 0, 82)); // NOI18N
        colon3.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        timePanel.add(colon3, gridBagConstraints);

        add(timePanel);

        jSeparator1.setMaximumSize(new java.awt.Dimension(640, 12));
        jSeparator1.setPreferredSize(new java.awt.Dimension(640, 12));
        add(jSeparator1);

        finishedTaskPanel.setBackground(new java.awt.Color(255, 255, 255));
        finishedTaskPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        finishedTaskPanel.setMaximumSize(new java.awt.Dimension(640, 88));
        finishedTaskPanel.setMinimumSize(new java.awt.Dimension(640, 88));
        finishedTaskPanel.setPreferredSize(new java.awt.Dimension(640, 88));

        jTextField9.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(175, 255, 175));
        jTextField9.setText("Finished Task");
        jTextField9.setBorder(null);

        jCheckBox9.setAlignmentY(0.0F);
        jCheckBox9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Green_Check_Mark_Icon.png"))); // NOI18N

        subtasksPanel0.setBackground(new java.awt.Color(255, 255, 255));
        subtasksPanel0.setMaximumSize(new java.awt.Dimension(64, 70));
        subtasksPanel0.setMinimumSize(new java.awt.Dimension(64, 70));
        subtasksPanel0.setSize(new java.awt.Dimension(64, 70));
        subtasksPanel0.setLayout(new java.awt.GridBagLayout());

        greenSpherejLabel0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        greenSpherejLabel0.setMaximumSize(new java.awt.Dimension(16, 16));
        greenSpherejLabel0.setMinimumSize(new java.awt.Dimension(16, 16));
        greenSpherejLabel0.setPreferredSize(new java.awt.Dimension(16, 16));
        subtasksPanel0.add(greenSpherejLabel0, new java.awt.GridBagConstraints());

        greenSpherejLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel0.add(greenSpherejLabel1, new java.awt.GridBagConstraints());

        greenSpherejLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        subtasksPanel0.add(greenSpherejLabel2, gridBagConstraints);

        greenSpherejLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        subtasksPanel0.add(greenSpherejLabel3, gridBagConstraints);

        greenSpherejLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel0.add(greenSpherejLabel4, new java.awt.GridBagConstraints());

        greenSpherejLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        subtasksPanel0.add(greenSpherejLabel5, gridBagConstraints);

        greenSpherejLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel0.add(greenSpherejLabel6, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout finishedTaskPanelLayout = new javax.swing.GroupLayout(finishedTaskPanel);
        finishedTaskPanel.setLayout(finishedTaskPanelLayout);
        finishedTaskPanelLayout.setHorizontalGroup(
            finishedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finishedTaskPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtasksPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        finishedTaskPanelLayout.setVerticalGroup(
            finishedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finishedTaskPanelLayout.createSequentialGroup()
                .addGroup(finishedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(finishedTaskPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jCheckBox9))
                    .addGroup(finishedTaskPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(finishedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(subtasksPanel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(finishedTaskPanel);

        currentTaskPanel.setBackground(new java.awt.Color(237, 255, 246));
        currentTaskPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 3));
        currentTaskPanel.setMaximumSize(new java.awt.Dimension(640, 88));
        currentTaskPanel.setMinimumSize(new java.awt.Dimension(640, 88));
        currentTaskPanel.setPreferredSize(new java.awt.Dimension(640, 88));

        subtasksPanel1.setBackground(new java.awt.Color(237, 255, 246));
        subtasksPanel1.setMaximumSize(new java.awt.Dimension(64, 70));
        subtasksPanel1.setMinimumSize(new java.awt.Dimension(64, 70));
        subtasksPanel1.setSize(new java.awt.Dimension(64, 70));
        subtasksPanel1.setLayout(new java.awt.GridBagLayout());

        greenSpherejLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel1.add(greenSpherejLabel7, new java.awt.GridBagConstraints());

        greenSpherejLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel1.add(greenSpherejLabel8, new java.awt.GridBagConstraints());

        greySpherejLabel0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        subtasksPanel1.add(greySpherejLabel0, new java.awt.GridBagConstraints());

        greySpherejLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        subtasksPanel1.add(greySpherejLabel1, gridBagConstraints);

        greySpherejLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        subtasksPanel1.add(greySpherejLabel2, gridBagConstraints);

        jTextField3.setBackground(new java.awt.Color(237, 255, 246));
        jTextField3.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField3.setText("Current Task");
        jTextField3.setBorder(null);

        javax.swing.GroupLayout currentTaskPanelLayout = new javax.swing.GroupLayout(currentTaskPanel);
        currentTaskPanel.setLayout(currentTaskPanelLayout);
        currentTaskPanelLayout.setHorizontalGroup(
            currentTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, currentTaskPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtasksPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        currentTaskPanelLayout.setVerticalGroup(
            currentTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subtasksPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(currentTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(currentTaskPanel);

        taskPendingPanel1.setBackground(new java.awt.Color(255, 255, 255));
        taskPendingPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        taskPendingPanel1.setMaximumSize(new java.awt.Dimension(640, 88));
        taskPendingPanel1.setMinimumSize(new java.awt.Dimension(640, 88));
        taskPendingPanel1.setPreferredSize(new java.awt.Dimension(640, 88));

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField1.setText("Pending Task");
        jTextField1.setBorder(null);
        jTextField1.setMaximumSize(new java.awt.Dimension(326, 70));
        jTextField1.setMinimumSize(new java.awt.Dimension(326, 70));

        jCheckBox1.setAlignmentY(0.0F);

        javax.swing.GroupLayout taskPendingPanel1Layout = new javax.swing.GroupLayout(taskPendingPanel1);
        taskPendingPanel1.setLayout(taskPendingPanel1Layout);
        taskPendingPanel1Layout.setHorizontalGroup(
            taskPendingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskPendingPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        taskPendingPanel1Layout.setVerticalGroup(
            taskPendingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskPendingPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskPendingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taskPendingPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskPendingPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)
                        .addGap(24, 24, 24))))
        );

        add(taskPendingPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel4.setMaximumSize(new java.awt.Dimension(640, 88));
        jPanel4.setMinimumSize(new java.awt.Dimension(640, 88));
        jPanel4.setPreferredSize(new java.awt.Dimension(640, 88));

        jTextField4.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField4.setText("Pending Task");
        jTextField4.setBorder(null);
        jTextField4.setMaximumSize(new java.awt.Dimension(326, 70));
        jTextField4.setMinimumSize(new java.awt.Dimension(326, 70));

        subtasksPanel2.setBackground(new java.awt.Color(255, 255, 255));
        subtasksPanel2.setMaximumSize(new java.awt.Dimension(64, 70));
        subtasksPanel2.setMinimumSize(new java.awt.Dimension(64, 70));
        subtasksPanel2.setSize(new java.awt.Dimension(64, 70));
        subtasksPanel2.setLayout(new java.awt.GridBagLayout());

        greenSpherejLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel2.add(greenSpherejLabel9, new java.awt.GridBagConstraints());

        greenSpherejLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel2.add(greenSpherejLabel10, new java.awt.GridBagConstraints());

        greenSpherejLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        subtasksPanel2.add(greenSpherejLabel11, gridBagConstraints);

        greenSpherejLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        subtasksPanel2.add(greenSpherejLabel12, gridBagConstraints);

        greenSpherejLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        subtasksPanel2.add(greenSpherejLabel13, new java.awt.GridBagConstraints());

        greenSpherejLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        subtasksPanel2.add(greenSpherejLabel14, gridBagConstraints);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(subtasksPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtasksPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel7.setMaximumSize(new java.awt.Dimension(640, 88));
        jPanel7.setMinimumSize(new java.awt.Dimension(640, 88));
        jPanel7.setPreferredSize(new java.awt.Dimension(640, 88));

        jTextField7.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField7.setText("Pending Task");
        jTextField7.setBorder(null);
        jTextField7.setMaximumSize(new java.awt.Dimension(326, 70));
        jTextField7.setMinimumSize(new java.awt.Dimension(326, 70));

        jCheckBox7.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jCheckBox7)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel7);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel5.setMaximumSize(new java.awt.Dimension(640, 88));
        jPanel5.setMinimumSize(new java.awt.Dimension(640, 88));
        jPanel5.setPreferredSize(new java.awt.Dimension(640, 88));

        jTextField5.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField5.setText("Pending Task");
        jTextField5.setBorder(null);
        jTextField5.setMaximumSize(new java.awt.Dimension(326, 70));
        jTextField5.setMinimumSize(new java.awt.Dimension(326, 70));

        jCheckBox5.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jCheckBox5)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(jPanel5);

        abandonedTaskPanel.setBackground(new java.awt.Color(255, 255, 234));
        abandonedTaskPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        abandonedTaskPanel.setMaximumSize(new java.awt.Dimension(640, 88));
        abandonedTaskPanel.setMinimumSize(new java.awt.Dimension(640, 88));
        abandonedTaskPanel.setPreferredSize(new java.awt.Dimension(640, 88));

        jTextField8.setBackground(new java.awt.Color(255, 255, 234));
        jTextField8.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(204, 204, 204));
        jTextField8.setText("Abandoned Task");
        jTextField8.setBorder(null);

        jCheckBox8.setAlignmentY(0.0F);

        javax.swing.GroupLayout abandonedTaskPanelLayout = new javax.swing.GroupLayout(abandonedTaskPanel);
        abandonedTaskPanel.setLayout(abandonedTaskPanelLayout);
        abandonedTaskPanelLayout.setHorizontalGroup(
            abandonedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abandonedTaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        abandonedTaskPanelLayout.setVerticalGroup(
            abandonedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abandonedTaskPanelLayout.createSequentialGroup()
                .addGroup(abandonedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abandonedTaskPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(abandonedTaskPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jCheckBox8)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(abandonedTaskPanel);

        failedTaskPanel.setBackground(new java.awt.Color(255, 244, 244));
        failedTaskPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        failedTaskPanel.setMaximumSize(new java.awt.Dimension(640, 88));
        failedTaskPanel.setMinimumSize(new java.awt.Dimension(640, 88));
        failedTaskPanel.setPreferredSize(new java.awt.Dimension(640, 88));

        jTextField6.setBackground(new java.awt.Color(255, 244, 244));
        jTextField6.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 0, 0));
        jTextField6.setText("Failed Task");
        jTextField6.setBorder(null);
        jTextField6.setMaximumSize(new java.awt.Dimension(326, 70));
        jTextField6.setMinimumSize(new java.awt.Dimension(326, 70));

        jCheckBox6.setAlignmentY(0.0F);
        jCheckBox6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/RedFail.png"))); // NOI18N

        subtasksPanel3.setBackground(new java.awt.Color(255, 244, 244));
        subtasksPanel3.setMaximumSize(new java.awt.Dimension(64, 70));
        subtasksPanel3.setMinimumSize(new java.awt.Dimension(64, 70));
        subtasksPanel3.setSize(new java.awt.Dimension(64, 70));
        subtasksPanel3.setLayout(new java.awt.GridBagLayout());

        greenSpherejLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel3.add(greenSpherejLabel15, new java.awt.GridBagConstraints());

        greenSpherejLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel3.add(greenSpherejLabel16, new java.awt.GridBagConstraints());

        greySpherejLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        subtasksPanel3.add(greySpherejLabel4, gridBagConstraints);

        greySpherejLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/SphereRed.gif"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        subtasksPanel3.add(greySpherejLabel5, gridBagConstraints);

        javax.swing.GroupLayout failedTaskPanelLayout = new javax.swing.GroupLayout(failedTaskPanel);
        failedTaskPanel.setLayout(failedTaskPanelLayout);
        failedTaskPanelLayout.setHorizontalGroup(
            failedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, failedTaskPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtasksPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        failedTaskPanelLayout.setVerticalGroup(
            failedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(failedTaskPanelLayout.createSequentialGroup()
                .addGroup(failedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(failedTaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(subtasksPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(failedTaskPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(failedTaskPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jCheckBox6)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(failedTaskPanel);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel11.setMaximumSize(new java.awt.Dimension(640, 88));
        jPanel11.setMinimumSize(new java.awt.Dimension(640, 88));
        jPanel11.setPreferredSize(new java.awt.Dimension(640, 88));

        jTextField11.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField11.setText("Pending Task");
        jTextField11.setBorder(null);

        subtasksPanel4.setBackground(new java.awt.Color(255, 255, 255));
        subtasksPanel4.setMaximumSize(new java.awt.Dimension(64, 70));
        subtasksPanel4.setMinimumSize(new java.awt.Dimension(64, 70));
        subtasksPanel4.setSize(new java.awt.Dimension(64, 70));
        subtasksPanel4.setLayout(new java.awt.GridBagLayout());

        greenSpherejLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel4.add(greenSpherejLabel17, new java.awt.GridBagConstraints());

        greenSpherejLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/Sphere_Green_16.png"))); // NOI18N
        subtasksPanel4.add(greenSpherejLabel18, new java.awt.GridBagConstraints());

        greenSpherejLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        subtasksPanel4.add(greenSpherejLabel20, gridBagConstraints);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtasksPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subtasksPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel12.setMaximumSize(new java.awt.Dimension(640, 88));
        jPanel12.setMinimumSize(new java.awt.Dimension(640, 88));
        jPanel12.setPreferredSize(new java.awt.Dimension(640, 88));

        jTextField12.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField12.setText("Pending Task");
        jTextField12.setBorder(null);

        jCheckBox12.setAlignmentY(0.0F);

        subtasksPanel5.setBackground(new java.awt.Color(255, 255, 255));
        subtasksPanel5.setMaximumSize(new java.awt.Dimension(64, 70));
        subtasksPanel5.setMinimumSize(new java.awt.Dimension(64, 70));
        subtasksPanel5.setSize(new java.awt.Dimension(64, 70));
        subtasksPanel5.setLayout(new java.awt.GridBagLayout());

        greySpherejLabel02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        subtasksPanel5.add(greySpherejLabel02, gridBagConstraints);

        greySpherejLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        subtasksPanel5.add(greySpherejLabel3, gridBagConstraints);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtasksPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox12)
                .addGap(25, 25, 25))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subtasksPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        add(jPanel12);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField10.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jTextField10.setText("Pending Task");
        jTextField10.setBorder(null);

        subtasksPanel6.setBackground(new java.awt.Color(255, 255, 255));
        subtasksPanel6.setMaximumSize(new java.awt.Dimension(64, 70));
        subtasksPanel6.setMinimumSize(new java.awt.Dimension(64, 70));
        subtasksPanel6.setSize(new java.awt.Dimension(64, 70));
        subtasksPanel6.setLayout(new java.awt.GridBagLayout());

        greySpherejLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        subtasksPanel6.add(greySpherejLabel6, gridBagConstraints);

        greySpherejLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/draw-sphere-icone-9132-16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        subtasksPanel6.add(greySpherejLabel7, gridBagConstraints);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subtasksPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subtasksPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel10);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abandonedTaskPanel;
    private javax.swing.JLabel colon1;
    private javax.swing.JLabel colon2;
    private javax.swing.JLabel colon3;
    private javax.swing.JPanel currentTaskPanel;
    private javax.swing.JLabel dayslab;
    private javax.swing.JLabel daysval;
    private javax.swing.JPanel failedTaskPanel;
    private javax.swing.JPanel finishedTaskPanel;
    private javax.swing.JLabel greenSpherejLabel0;
    private javax.swing.JLabel greenSpherejLabel1;
    private javax.swing.JLabel greenSpherejLabel10;
    private javax.swing.JLabel greenSpherejLabel11;
    private javax.swing.JLabel greenSpherejLabel12;
    private javax.swing.JLabel greenSpherejLabel13;
    private javax.swing.JLabel greenSpherejLabel14;
    private javax.swing.JLabel greenSpherejLabel15;
    private javax.swing.JLabel greenSpherejLabel16;
    private javax.swing.JLabel greenSpherejLabel17;
    private javax.swing.JLabel greenSpherejLabel18;
    private javax.swing.JLabel greenSpherejLabel2;
    private javax.swing.JLabel greenSpherejLabel20;
    private javax.swing.JLabel greenSpherejLabel3;
    private javax.swing.JLabel greenSpherejLabel4;
    private javax.swing.JLabel greenSpherejLabel5;
    private javax.swing.JLabel greenSpherejLabel6;
    private javax.swing.JLabel greenSpherejLabel7;
    private javax.swing.JLabel greenSpherejLabel8;
    private javax.swing.JLabel greenSpherejLabel9;
    private javax.swing.JLabel greySpherejLabel0;
    private javax.swing.JLabel greySpherejLabel02;
    private javax.swing.JLabel greySpherejLabel1;
    private javax.swing.JLabel greySpherejLabel2;
    private javax.swing.JLabel greySpherejLabel3;
    private javax.swing.JLabel greySpherejLabel4;
    private javax.swing.JLabel greySpherejLabel5;
    private javax.swing.JLabel greySpherejLabel6;
    private javax.swing.JLabel greySpherejLabel7;
    private javax.swing.JLabel hrslab;
    private javax.swing.JLabel hrsval;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel minlab;
    private javax.swing.JLabel minval;
    private javax.swing.JLabel plusminus;
    private javax.swing.JLabel seclab;
    private javax.swing.JLabel secval;
    private javax.swing.JPanel subtasksPanel0;
    private javax.swing.JPanel subtasksPanel1;
    private javax.swing.JPanel subtasksPanel2;
    private javax.swing.JPanel subtasksPanel3;
    private javax.swing.JPanel subtasksPanel4;
    private javax.swing.JPanel subtasksPanel5;
    private javax.swing.JPanel subtasksPanel6;
    private javax.swing.JPanel taskPendingPanel1;
    private javax.swing.JPanel timePanel;
    private javax.swing.JLabel warninglab;
    // End of variables declaration//GEN-END:variables
}
