/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hymerfania.countdown_mockups;

/**
 *
 * @author chymes
 */
public class TaskDetail extends javax.swing.JPanel {

    /**
     * Creates new form TaskDetail
     */
    public TaskDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        durationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        durationTimePanel = new javax.swing.JPanel();
        dayVal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hrlVal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        minVal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        secVal = new javax.swing.JLabel();
        duePanel = new javax.swing.JPanel();
        dueLabel = new javax.swing.JLabel();
        dueTimePanel = new javax.swing.JPanel();
        minusLable = new javax.swing.JLabel();
        dayVal2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hrlVal2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        minVal2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        secVal2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stepPanelA = new javax.swing.JPanel();
        stepLabel1 = new javax.swing.JLabel();
        stepPanelB = new javax.swing.JPanel();
        stepLabel = new javax.swing.JLabel();
        stepPanelC = new javax.swing.JPanel();
        stepLabel2 = new javax.swing.JLabel();
        stepPanelD = new javax.swing.JPanel();
        stepLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(640, 1136));
        setMinimumSize(new java.awt.Dimension(640, 1136));
        setPreferredSize(new java.awt.Dimension(640, 1136));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 82)); // NOI18N
        jLabel1.setText("Pack Parachute");

        durationPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Duration:");

        durationTimePanel.setBackground(new java.awt.Color(255, 255, 255));
        durationTimePanel.setLayout(new java.awt.GridBagLayout());

        dayVal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        dayVal.setText("00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        durationTimePanel.add(dayVal, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        durationTimePanel.add(jLabel4, gridBagConstraints);

        hrlVal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        hrlVal.setText("00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        durationTimePanel.add(hrlVal, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        durationTimePanel.add(jLabel6, gridBagConstraints);

        minVal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        minVal.setText("05");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        durationTimePanel.add(minVal, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        durationTimePanel.add(jLabel7, gridBagConstraints);

        secVal.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        secVal.setText("30");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        durationTimePanel.add(secVal, gridBagConstraints);

        javax.swing.GroupLayout durationPanelLayout = new javax.swing.GroupLayout(durationPanel);
        durationPanel.setLayout(durationPanelLayout);
        durationPanelLayout.setHorizontalGroup(
            durationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(durationTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        durationPanelLayout.setVerticalGroup(
            durationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(durationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(durationTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
        );

        duePanel.setBackground(new java.awt.Color(255, 255, 255));

        dueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        dueLabel.setText("Due:");

        dueTimePanel.setBackground(new java.awt.Color(255, 255, 255));
        dueTimePanel.setLayout(new java.awt.GridBagLayout());

        minusLable.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        minusLable.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        dueTimePanel.add(minusLable, gridBagConstraints);

        dayVal2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        dayVal2.setText("00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        dueTimePanel.add(dayVal2, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        dueTimePanel.add(jLabel10, gridBagConstraints);

        hrlVal2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        hrlVal2.setText("00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        dueTimePanel.add(hrlVal2, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        dueTimePanel.add(jLabel11, gridBagConstraints);

        minVal2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        minVal2.setText("18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        dueTimePanel.add(minVal2, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        dueTimePanel.add(jLabel12, gridBagConstraints);

        secVal2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        secVal2.setText("64");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        dueTimePanel.add(secVal2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel3.setText("2:15 pm, Sat, Jul 11 2015");

        javax.swing.GroupLayout duePanelLayout = new javax.swing.GroupLayout(duePanel);
        duePanel.setLayout(duePanelLayout);
        duePanelLayout.setHorizontalGroup(
            duePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(duePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dueTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        duePanelLayout.setVerticalGroup(
            duePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, duePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(duePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(duePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dueTimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dueLabel))))
        );

        stepPanelA.setBackground(new java.awt.Color(255, 255, 255));
        stepPanelA.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        stepLabel1.setBackground(new java.awt.Color(255, 255, 255));
        stepLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/parachute_a.png"))); // NOI18N

        javax.swing.GroupLayout stepPanelALayout = new javax.swing.GroupLayout(stepPanelA);
        stepPanelA.setLayout(stepPanelALayout);
        stepPanelALayout.setHorizontalGroup(
            stepPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stepPanelALayout.setVerticalGroup(
            stepPanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepPanelALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stepPanelB.setBackground(new java.awt.Color(255, 255, 255));
        stepPanelB.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        stepLabel.setBackground(new java.awt.Color(255, 255, 255));
        stepLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/parachute_b.png"))); // NOI18N

        javax.swing.GroupLayout stepPanelBLayout = new javax.swing.GroupLayout(stepPanelB);
        stepPanelB.setLayout(stepPanelBLayout);
        stepPanelBLayout.setHorizontalGroup(
            stepPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepPanelBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stepPanelBLayout.setVerticalGroup(
            stepPanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepPanelBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stepPanelC.setBackground(new java.awt.Color(255, 255, 255));
        stepPanelC.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        stepLabel2.setBackground(new java.awt.Color(255, 255, 255));
        stepLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/parachute_c.png"))); // NOI18N

        javax.swing.GroupLayout stepPanelCLayout = new javax.swing.GroupLayout(stepPanelC);
        stepPanelC.setLayout(stepPanelCLayout);
        stepPanelCLayout.setHorizontalGroup(
            stepPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stepPanelCLayout.setVerticalGroup(
            stepPanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepPanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stepPanelD.setBackground(new java.awt.Color(255, 255, 255));
        stepPanelD.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        stepLabel3.setBackground(new java.awt.Color(255, 255, 255));
        stepLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hymerfania/countdown_mockups/resources/parachute_d.png"))); // NOI18N

        javax.swing.GroupLayout stepPanelDLayout = new javax.swing.GroupLayout(stepPanelD);
        stepPanelD.setLayout(stepPanelDLayout);
        stepPanelDLayout.setHorizontalGroup(
            stepPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepPanelDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stepPanelDLayout.setVerticalGroup(
            stepPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepPanelDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(durationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(stepPanelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
                    .addComponent(stepPanelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stepPanelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stepPanelD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(stepPanelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepPanelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepPanelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stepPanelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(534, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayVal;
    private javax.swing.JLabel dayVal2;
    private javax.swing.JLabel dueLabel;
    private javax.swing.JPanel duePanel;
    private javax.swing.JPanel dueTimePanel;
    private javax.swing.JPanel durationPanel;
    private javax.swing.JPanel durationTimePanel;
    private javax.swing.JLabel hrlVal;
    private javax.swing.JLabel hrlVal2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel minVal;
    private javax.swing.JLabel minVal2;
    private javax.swing.JLabel minusLable;
    private javax.swing.JLabel secVal;
    private javax.swing.JLabel secVal2;
    private javax.swing.JLabel stepLabel;
    private javax.swing.JLabel stepLabel1;
    private javax.swing.JLabel stepLabel2;
    private javax.swing.JLabel stepLabel3;
    private javax.swing.JPanel stepPanelA;
    private javax.swing.JPanel stepPanelB;
    private javax.swing.JPanel stepPanelC;
    private javax.swing.JPanel stepPanelD;
    // End of variables declaration//GEN-END:variables
}
